<template>
	<form>
		<nms-upload name="planet_image_upload" @change.native="fileSelected($event)"></nms-upload>
		<galaxy-select search="true" label="Select a galaxy" name="galaxy_select" v-model="filled.galaxy"></galaxy-select>
		<nms-input v-model="filled.planet" label="Planet Name" name="planet" kind="text"></nms-input>
		<nms-select search="true" v-model="filled.type" name="planet_biome" label="What biome does the planet have?" :options="biomes"></nms-select>
		<nms-select search="true" v-model="filled.weather" name="planet_weather" label="What weather is on the planet?" :options="weathertypes"></nms-select>
		<nms-select v-model="filled.sentinels" name="planet_sentinels" label="How are the sentinels?" :options="sentinels"></nms-select>
		<nms-input name="planet_flora" v-model="filled.flora" kind="text" label="What's the Flora status?"></nms-input>
		<nms-input name="planet_fauna" v-model="filled.fauna" kind="text" label="What's the Fauna status?"></nms-input>
		<nms-input v-model="filled.description" kind="textarea" label="What's so awesome about this planet?"></nms-input>
		<glyph-selector v-model="filled.glyphs" label="Enter the portal glyph combination"></glyph-selector>
		<nms-button @click.native="submitPost" class="nms__form-planet--submit" color="green">Submit post</nms-button>
	</form>
</template>

<script>
	import GlyphSelector from '@/components/custom/GlyphSelector.vue';
	import GalaxySelect from '@/components/UI/Selects/GalaxySelect.vue';
	export default {
		components: {
			'glyph-selector': GlyphSelector,
			'galaxy-select': GalaxySelect
		},
		data() {
			return {
				biomes: ['Scorched', 'Frozen', 'Toxic', 'Irradiated', 'Arid', 'Bleak', 'Corrosive', 'Dead', 'Desert',
					'Forsaken', 'Galcial', 'Lifeless', 'Noxious', 'Poisonous', 'Sub-zero', 'Tropical',
					'Viridiscent', 'Incandescent'
				],
				weathertypes: [
					"Absent",
					"Acid Rain",
					"Acidic Deluges",
					"Acidic Dust",
					"Acidic Dust Pockets",
					"Airless",
					"Alkaline Cloudbursts",
					"Alkaline Rain",
					"Alkaline Storms",
					"Anomalous",
					"Arid",
					"Atmospheric Corruption",
					"Atmospheric Heat Instabilities",
					"Baked",
					"Balmy",
					"Beautiful",
					"Bilious Storms",
					"Billowing Dust Storms",
					"Blasted Atmosphere",
					"Blazed",
					"Blissful",
					"Blistering Damp",
					"Blistering Floods",
					"Blizzard",
					"Blood Rain",
					"Boiling Monsoons",
					"Boiling Puddles",
					"Boiling Superstorms",
					"Bone-Stripping Acid Storms",
					"Broiling Humidity",
					"Burning",
					"Burning Air",
					"Burning Gas Clouds",
					"Caustic Dust",
					"Caustic Floods",
					"Caustic Moisture",
					"Caustic Winds",
					"Ceaseless Drought",
					"Choking Clouds",
					"Choking Humidity",
					"Choking Sandstorms",
					"Clear",
					"Cold",
					"Combustible Dust",
					"Contaminated",
					"Contaminated Puddles",
					"Contaminated Squalls",
					"Corrosive Cyclones",
					"Corrosive Damp",
					"Corrosive Rainstorms",
					"Corrosive Sleet Storms",
					"Corrosive Storms",
					"Crimson Heat",
					"Crisp",
					"Damp",
					"Dangerously Hot",
					"Dangerously Hot Fog",
					"Dangerously Toxic Rain",
					"Dead Wastes",
					"Deep Freeze",
					"Dehydrated",
					"Deluge",
					"Desolate",
					"Desiccated",
					"Direct Sunlight",
					"Downpours",
					"Drifting Snowstorms",
					"Drizzle",
					"Droughty",
					"Dry Gusts",
					"Dust-Choked Winds",
					"Eerily Calm",
					"Electric Rain",
					"Elevated Radioactivity",
					"Emollient",
					"Energetic Storms",
					"Enormous Nuclear Storms",
					"Extreme Acidity",
					"Extreme Atmospheric Decay",
					"Extreme Cold",
					"Extreme Contamination",
					"Extreme Heat",
					"Extreme Nuclear Decay",
					"Extreme Radioactivity",
					"Extreme Thermonuclear Fog",
					"Extreme Toxicity",
					"Extreme Wind Blasting",
					"Extreme Winds",
					"Fair",
					"Fine",
					"Firestorms",
					"Flaming Hail",
					"Freezing",
					"Freezing Night Winds",
					"Freezing Rain",
					"Frequent Blizzards",
					"Frequent Particle Eruptions",
					"Frequent Toxic Floods",
					"Frigid",
					"Frost",
					"Frozen",
					"Frozen Clouds",
					"Gamma Cyclones",
					"Gamma Dust",
					"Gas Clouds",
					"Gelid",
					"Glacial",
					"Harmful Rain",
					"Harsh Winds",
					"Harsh, Icy Winds",
					"Haunted Frost",
					"Hazardous Temperature Extremes",
					"Hazardous Whiteouts",
					"Heated",
					"Heated Atmosphere",
					"Heavily Toxic Rain",
					"Heavy Rain",
					"Highly Variable Temperatures",
					"Hot",
					"Howling Blizzards",
					"Howling Gales",
					"Humid",
					"Ice Storms",
					"Icebound",
					"Icy",
					"Icy Blasts",
					"Icy Nights",
					"Icy Tempests",
					"Incendiary Dust",
					"Indetectable Burning",
					"Inert",
					"Inferno",
					"Inferno Winds",
					"Infrequent Blizzards",
					"Infrequent Dust Storms",
					"Infrequent Heat Storms",
					"Infrequent Toxic Drizzle",
					"Intense Cold",
					"Intense Dust",
					"Intense Heat",
					"Intense Heatbursts",
					"Intense Rainfall",
					"Intermittent Wind Blasting",
					"Internal Rain",
					"Invisible Mist",
					"Irradiated",
					"Irradiated Downpours",
					"Irradiated Storms",
					"Irradiated Thunderstorms",
					"Irradiated Winds",
					"Lethal Atmosphere",
					"Lethal Humidity Outbreaks",
					"Light Showers",
					"Lost Clouds",
					"Lung-Burning Night Wind",
					"Mellow",
					"Memories of Frost",
					"Migratory Blizzards",
					"Mild",
					"Mild Rain",
					"Moderate",
					"Moistureless",
					"Monsoon",
					"Mostly Calm",
					"No Atmosphere",
					"Noxious Gas Storms",
					"Noxious Gases",
					"Nuclear Emission",
					"Nuclidic Atmosphere",
					"Obsidian Heat",
					"Occasional Acid Storms",
					"Occasional Ash Storms",
					"Occasional Radiation Outbursts",
					"Occasional Sandstorms",
					"Occasional Scalding Cloudbursts",
					"Occasional Snowfall",
					"Outbreaks of Frozen Rain",
					"Overly Warm",
					"Painfully Hot Rain",
					"Parched",
					"Parched Sands",
					"Particulate Winds",
					"Passing Toxic Fronts",
					"Peaceful",
					"Peaceful Climate",
					"Perfectly Clear",
					"Permafrost",
					"Planet-Wide Radiation Storms",
					"Planetwide Desiccation",
					"Pleasant",
					"Poison Flurries",
					"Poison Rain",
					"Poisonous Dust",
					"Poisonous Gas",
					"Pouring Rain",
					"Pouring Toxic Rain",
					"Powder Snow",
					"Radioactive",
					"Radioactive Damp",
					"Radioactive Decay",
					"Radioactive Dust Storms",
					"Radioactive Humidity",
					"Radioactive Storms",
					"Radioactivity",
					"Raging Snowstorms",
					"Rain of Atlas",
					"Rainstorms",
					"Rare Firestorms",
					"Reactive",
					"Reactive Dust",
					"Reactive Rain",
					"Refreshing Breeze",
					"Roaring Ice Storms",
					"Roaring Nuclear Wind",
					"Sand Blizzards",
					"Sandstorms",
					"Scalding Heat",
					"Scaling Rainstorms",
					"Scorched",
					"Self-Igniting Storms",
					"Silent",
					"Smouldering",
					"Snow",
					"Snowfall",
					"Snowstorms",
					"Snowy",
					"Sporadic Grit Storms",
					"Sterile",
					"Stinging Atmosphere",
					"Stinging Puddles",
					"Sunny",
					"Supercooled Storms",
					"Superheated Air",
					"Superheated Drizzle",
					"Superheated Gas Pockets",
					"Superheated Rain",
					"Sweltering",
					"Sweltering Damp",
					"Temperate",
					"Tempered",
					"Thirsty Clouds",
					"Torrential Acid",
					"Torrential Heat",
					"Torrential Rain",
					"Torrid Deluges",
					"Toxic Clouds",
					"Toxic Damp",
					"Toxic Dust",
					"Toxic Monsoons",
					"Toxic Outbreaks",
					"Toxic Rain",
					"Toxic Superstorms",
					"Tropical Storms",
					"Unclouded Skies",
					"Unending Sunlight",
					"Unstable",
					"Unstable Atmosphere",
					"Unstable Fog",
					"Unusually Mild",
					"Usually Mild",
					"Utterly Still",
					"Volatile",
					"Volatile Dust Storms",
					"Volatile Storms",
					"Volatile Winds",
					"Volatile Windstorms",
					"Wandering Frosts",
					"Wandering Hot Spots",
					"Warm",
					"Wet",
					"Whiteout",
					"Wind",
					"Winds of Glass",
					"Wintry",
					"Withered"
				],
				sentinels: ['Passive', 'Lacking', 'Relaxed', 'Limited', 'Low', 'Low Security', 
				'Minimal', 'Active', 'Average', 'Standard', 'Typical', 'Mindful', 'Engaging', 
				'Frenzied', 'High Security', 'Aggresive', 'Hostile'],
				filled: {
					postType: 'planets',
					image: null,
					type: null,
					weather: null,
					sentinels: null,
					flora: null,
					fauna: null,
					planet: null,
					glyphs: null,
					galaxy: null,
					description: null
				}
			}
		},
		methods: {
			fileSelected(e) {
				if (e.target.files[0].size < 1000000) {
					this.filled.image = e.target.files[0];
					this.filled.image.id = +new Date() + this.filled.image.name.replace(/\s/g, '-');
				}
			},
			uploadFile() {
				if (this.filled.image !== '') {
					document.querySelector('body').classList.add('loading');
					this.$store.dispatch('newpost/new-post/uploadFile', this.filled.image);
				}
			},
			submitPost() {
				if(
					this.evaluateInput(this.filled.image === null, "planet_image_upload", "Please upload an image") &&
					this.evaluateInput(this.filled.galaxy === null, "galaxy_select", "Please select a galaxy") &&
					this.evaluateInput(this.filled.planet === null, "planet", "Please enter the planet's name") &&
					this.evaluateInput(this.filled.type === null, "planet_biome", "Please select a planet biome before submitting") &&
					this.evaluateInput(this.filled.weather === null, "planet_weather", "Please enter the planet's weather") &&
					this.evaluateInput(this.filled.sentinels === null, "planet_sentinels", "Please enter the planet's sentinel level") &&
					this.evaluateInput(this.filled.flora === null, "planet_flora", "Please enter the planet's flora") &&
					this.evaluateInput(this.filled.fauna === null, "planet_fauna", "Please enter the planet's fauna") &&
					this.evaluateInput(this.filled.glyphs === null, "glyph__selector", "Please enter the portal glyphs")
				) {
					document.querySelector('body').classList.add('loading');
					this.$store.dispatch('newpost/new-post/submitNewPost', this.filled);
				}
			}
		}
	}
</script>
<style scoped lang='scss'>
	
</style>